In [5]:
from pathlib import Path
import pandas as pd

In [2]:
# TODO download from https://www.doogal.co.uk/files/postcodes.zip
# !!! the raw file is huge, it's about 1.9GB
POSTCODES_FOLDER = Path("../../temp/postcodes")
POSTCODES_PATH = POSTCODES_FOLDER / Path("postcodes.csv")

In [10]:
# Load first 1000 postcodes
postcodes_df = (pd.read_csv(POSTCODES_PATH)[lambda df: df["In Use?"].eq("Yes")])

print(postcodes_df.columns )
postcodes_df.head()

C:\Users\akoss\AppData\Local\Temp\ipykernel_21508\3466195296.py:2: DtypeWarning: Columns (7,17,18,21,22,24,29,32,39,47,51,53,54,55,56,57) have mixed types. Specify dtype option on import or set low_memory=False.
  postcodes_df = (pd.read_csv(POSTCODES_PATH)[lambda df: df["In Use?"].eq("Yes")])

Index(['Postcode', 'In Use?', 'Latitude', 'Longitude', 'Easting', 'Northing',
       'Grid Ref', 'County', 'District', 'Ward', 'District Code', 'Ward Code',
       'Country', 'County Code', 'Constituency', 'Introduced', 'Terminated',
       'Parish', 'National Park', 'Population', 'Households', 'Built up area',
       'Built up sub-division', 'Lower layer super output area', 'Rural/urban',
       'Region', 'Altitude', 'London zone', 'LSOA Code', 'Local authority',
       'MSOA Code', 'Middle layer super output area', 'Parish Code',
       'Census output area', 'Constituency Code',
       'Index of Multiple Deprivation', 'Quality', 'User Type', 'Last updated',
       'Nearest station', 'Distance to station', 'Postcode area',
       'Postcode district', 'Police force', 'Water company', 'Plus Code',
       'Average Income', 'Sewage Company', 'Travel To Work Area',
       'ITL level 2', 'ITL level 3', 'UPRNs', 'Distance to sea', 'LSOA21 Code',
       'Lower layer super output area 2021', 'MSOA21 Code',
       'Middle layer super output area 2021', 'Census output area 2021'],
      dtype='object')

,Postcode,In Use?,Latitude,Longitude,Easting,Northing,Grid Ref,County,District,Ward,...,Travel To Work Area,ITL level 2,ITL level 3,UPRNs,Distance to sea,LSOA21 Code,Lower layer super output area 2021,MSOA21 Code,Middle layer super output area 2021,Census output area 2021
2656,AB10 1AB,Yes,57.149606,-2.096916,394235.0,806529.0,NJ942065,NaN,Aberdeen City,George St/Harbour,...,Aberdeen,North Eastern Scotland,Aberdeen City and Aberdeenshire,9051081797,2.07523,NaN,NaN,NaN,NaN,NaN
2658,AB10 1AF,Yes,57.149590,-2.096923,394235.0,806527.0,NJ942065,NaN,Aberdeen City,George St/Harbour,...,Aberdeen,North Eastern Scotland,Aberdeen City and Aberdeenshire,10092038405,2.07654,NaN,NaN,NaN,NaN,NaN
2659,AB10 1AG,Yes,57.149051,-2.097004,394230.0,806467.0,NJ942064,NaN,Aberdeen City,George St/Harbour,...,Aberdeen,North Eastern Scotland,Aberdeen City and Aberdeenshire,"9051146571,9051311832,9051312764",2.11082,NaN,NaN,NaN,NaN,NaN
2660,AB10 1AH,Yes,57.149590,-2.096923,394235.0,806527.0,NJ942065,NaN,Aberdeen City,George St/Harbour,...,Aberdeen,North Eastern Scotland,Aberdeen City and Aberdeenshire,"9051082459,10092038796",2.07654,NaN,NaN,NaN,NaN,NaN
2662,AB10 1AL,Yes,57.150058,-2.095916,394296.0,806579.0,NJ942065,NaN,Aberdeen City,George St/Harbour,...,Aberdeen,North Eastern Scotland,Aberdeen City and Aberdeenshire,"9051081963,9051121803,9051137831,9051145706",1.98563,NaN,NaN,NaN,NaN,NaN

In [11]:
postcodes_df.to_csv(POSTCODES_FOLDER / Path("postcodes_inuse.csv"), index=False)

In [23]:
# Get human readable data
postcodes_filtered_df = postcodes_df[['Postcode', 'Built up area',
       'County', 'District', 'Ward',
       'Country', 'Constituency']].copy()
# remove spaces from Postcodes
postcodes_filtered_df['Postcode'] = postcodes_filtered_df['Postcode'].str.replace(' ', '')
postcodes_filtered_df.head()

,Postcode,Built up area,County,District,Ward,Country,Constituency
2656,AB101AB,NaN,NaN,Aberdeen City,George St/Harbour,Scotland,Aberdeen North
2658,AB101AF,NaN,NaN,Aberdeen City,George St/Harbour,Scotland,Aberdeen North
2659,AB101AG,NaN,NaN,Aberdeen City,George St/Harbour,Scotland,Aberdeen North
2660,AB101AH,NaN,NaN,Aberdeen City,George St/Harbour,Scotland,Aberdeen North
2662,AB101AL,NaN,NaN,Aberdeen City,George St/Harbour,Scotland,Aberdeen North

In [24]:
postcodes_filtered_df.to_csv(POSTCODES_FOLDER / Path("postcodes_inuse_filtered.csv"), index=False)